addSbtPlugin("com.alejandrohdezma"       % "sbt-me"         % "0.3.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-fix"        % "0.2.4")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.4.31")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.9")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.0.2")
