addSbtPlugin("com.alejandrohdezma"       % "sbt-github-mdoc"          % "0.6.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-github-header"        % "0.6.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-fix"                  % "0.4.0")
addSbtPlugin("com.alejandrohdezma"       % "sbt-remove-test-from-pom" % "0.1.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"           % "1.5.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.11")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                 % "2.1.3")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"               % "5.5.0")
